### ISSUE TITLE
申请加入 Rust TT 翻译小组

### ISSUE THREAD

**Issue by asur4s** [studyrs/RustTT#1]
### 英文水平和写作能力

- 英语水平：大学英语四级。
- 写作能力：大学之后很少写作，希望能在后续翻译的工作中提高自己的写作能力。

### 社区预期参与程度

期望能实现两周一篇，目前经验不足，无法预估时间。

### 你对我们有哪些预期?

希望可以多多交流、分享经验。

**Comment by sunface** [comment]
好的，欢迎加入，经验不足可以学习，问题不大🤗
