### ISSUE TITLE
申请加入 Rust TT 翻译小组

### ISSUE THREAD

**Issue by minikiller** [studyrs/RustTT#3]
### 英文水平和写作能力

英文阅读能力完全没有问题，多年从事软件开发工作，浏览国外技术文章，通过CET-6级考试。但写作能力应该没有经验，希望可以在工作中得到进步。

### 社区预期参与程度

预计一个月至少一篇文章吧。

### 留一个联系方式

微信：minikiller70

### 如果可以，请附上你之前比较得意的翻译作品( optional )

没专门翻译过国外的文章

### 你对我们有哪些预期?

希望这个项目可以长期坚持做下去，不要半途而废。

**Comment by sunface** [comment]
放心，这个项目会一直做下去～～欢迎加入
