### ISSUE TITLE
申请加入 Rust TT 翻译小组

### ISSUE THREAD

**Issue by Cerdore** [studyrs/RustTT#4]
### 英文水平和写作能力

CET-4: 510, CET-6: 483.

写作方面，整理过一个大数据系统的实验手册。
部分文章list：

- https://zhuanlan.zhihu.com/p/350033189
- https://blog.csdn.net/khn64/article/details/120005525?spm=1001.2014.3001.5502[没好好校对，机翻比较明显]

### 社区预期参与程度

至少一个月一篇吧

### 留一个联系方式

qq: 648038087

### 你对我们有哪些预期?

其实还是抱着对自己的预期来参与这个活动，希望借这个机会能多学一点rust的知识。

**Comment by sunface** [comment]
手翻可以全方位提升能力哦，个人深度体悟。anyway, 欢迎加入 :)
