### ISSUE TITLE
申请加入 Rust TT 翻译小组

### ISSUE THREAD

**Issue by Facefall** [studyrs/RustTT#5]
### 英文水平和写作能力

英语水平：大学英语六级，雅思 6.5，日常阅读 rust 官方文档无障碍，日常会浏览 JavaScript weekly、quora、youtube。

写作能力：具备基本表达能力，但整体比较一般，写完后需要反复修改打磨。之前总结过一篇关于前端 ESM 与 Vite 的[文章](https://sulfuric-honeydew-d20.notion.site/Vite-8b365f1e003c43e9a87dcbf6cf167b94)。

### 社区预期参与程度

之前未有参与过，不太了解，视工作程度而定。但每周周末会有至少一天时间能进行参与社区翻译工作。

### 留一个联系方式

已在社区群中

### 如果可以，请附上你之前比较得意的翻译作品( optional )

没有

### 你对我们有哪些预期?

希望翻译出来的作品能帮助到中国人。
也希望能对自己有提升。

**Comment by sunface** [comment]
链接的文章拜读了下，相当不错了🤣 ，欢迎加入。

QQ群里找不到你
